name: Arch machine compiler
on:
  workflow_dispatch:

jobs:
  kernel_compiler:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup depencies and Toolchain
        run: |
          curl -LSs "https://raw.githubusercontent.com/${{ github.repository_owner }}/linux_playground/refs/heads/${{ github.ref_name }}/toolchain.sh" | bash
      - name: Kernel setup and compile
        run: |
          curl -LSs "https://raw.githubusercontent.com/${{ github.repository_owner }}/linux_playground/refs/heads/${{ github.ref_name }}/kernel.sh" | bash
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: Image.gz
          path: ${{ github.workspace }}/kernel/out/arch/arm64/boot/Image.gz
      - name: Send Via Telegram
        uses: BorisTestov/tg_sender_action@latest
        env:
          TG_SENDER_TG_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TG_SENDER_TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TG_SENDER_PAYLOAD_MESSAGE: Moonbeam Gale Kernel
          TG_SENDER_PAYLOAD_FILE_PATH: ${{ github.workspace }}/kernel/out/arch/arm64/boot/Image.gz
        
