name: Arch machine compiler
on:
  workflow_dispatch:

jobs:
  kernel_compiler:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup depencies and Toolchain
        run: |
          curl -LSs "https://raw.githubusercontent.com/${{ github.repository_owner }}/linux_playground/refs/heads/private2/toolchain.sh" | bash
      - name: Kernel setup and compile
        run: |
          curl -LSs "https://raw.githubusercontent.com/${{ github.repository_owner }}/linux_playground/refs/heads/private2/kernel.sh" | bash
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: Image.gz
          path: ${{ github.workspace }}/kernel/out/arch/arm64/boot/Image.gz
      - name: Send Via Telegram
        uses: appleboy/telegram-action@v1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "Moonbeam Gale Kernel"
          document: "kernel/out/arch/arm64/boot/Image.gz"

